### ISSUE TITLE
Jakarta Messaging 3.0 Specification Release Review was successful -- Final checklist items

### ISSUE THREAD

**Issue by edbratt** [eclipse-ee4j/jms-api#286]
Jakarta Messaging 3.0 release ballot has completed and has been accepted.  Congratulations and thank you for your contributions so far. Please perform the following actions to finalize and finish this release.
 - [x] promote api staging release; promote the specification api jars to maven central. An example release job script can be found here https://wiki.eclipse.org/MavenReleaseScript.
 - [x] go through the merged jakarta.ee specification website page to verify all the links are valid.
 - [x] approve the compatibility request.
 - [x] The compatible implementation project/vendor MUST send an email to tck@eclipse.org for approval of the compatible implementation for trademark usage.
 - [x] merge any final release branch as appropriate for the branch management for the project.

**Comment by dblevins** [comment]
I'll let someone from Open MQ execute "The compatible implementation project/vendor MUST send an email to tck@eclipse.org for approval of the compatible implementation for trademark usage."

**Comment by arjantijms** [comment]
I just sent the mail, cc'ing @dblevins

**Comment by arjantijms** [comment]
At the moment https://jakarta.ee/specifications/messaging/3.0/ still points to the milestone, but this typically takes some time to be updated.

**Comment by arjantijms** [comment]
Verified jars are in maven central: https://repo1.maven.org/maven2/jakarta/jms/jakarta.jms-api/3.0.0/

**Comment by edbratt** [comment]
> 
> 
> At the moment https://jakarta.ee/specifications/messaging/3.0/ still points to the milestone, but this typically takes some time to be updated.

You could verify using the netlify preview, [here](https://deploy-preview-303--jakartaee-specifications.netlify.app/specifications/messaging/3.0/) -- or just wait for the site to refresh (it does seem to be taking a long time).

**Comment by dblevins** [comment]
I've gone through the netlify specification website page and verified all the links are valid.  I'll leave it unchecked till we actually see that page live, however.

**Comment by dblevins** [comment]
Page is updated now and looks good.
